version: "3.7"
services:
  mysql-service:
    container_name: mysql-service
    image: mysql:8.0.27
#    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3307:3306
    volumes:
      - /var/lib/mysql:/var/lib/mysql
      - /etc/mysql/mysql.conf.d:/etc/mysql/conf.d
      - /etc/init.d/mysql:/etc/init.d/mysql
      - /var/log/mysql/error.log:/var/log/mysql/error.log
      - /var/run/mysqld/mysqld.sock:/var/run/mysqld/mysql.sock
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: test11_client_jenkins
      MYSQL_USER: root
      MYSQL_PASSWORD: Zerkalo82
      MYSQL_ROOT_PASSWORD: Zerkalo82
    restart: always
    networks:
      - test11

  test11_client_jenkins:
    container_name: test11_client_jenkins-service
    image: registry.hub.docker.com/solnce52004/test11_client_jenkins:latest
#    build:
#      context: .
#      dockerfile: ./docker/app/Dockerfile
    ports:
      - 188.212.125.157:5443:4443
    volumes:
      - .:/test11_client_jenkins
      - ./logs:/test11_client_jenkins/logs
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-service:3306/test11_client_jenkins
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Zerkalo82
    links:
      - mysql-service
    depends_on:
      - mysql-service
    restart: on-failure
    networks:
      - test11

networks:
  test11:
    external: true
    name: test11
    driver: bridge

