version: "3.7"
services:
  mysql-service:
    container_name: mysql-service
    image: mysql:8.0.27
    ports:
      - 3307:3306
    volumes:
      - /var/lib/mysql:/var/lib/mysql
      - /etc/mysql/mysql.conf.d:/etc/mysql/conf.d
      - /etc/init.d/mysql:/etc/init.d/mysql
      - /var/log/mysql/error.log:/var/log/mysql/error.log
      - /var/run/mysqld/mysqld.sock:/var/run/mysqld/mysql.sock
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: test11_client_jenkins
      MYSQL_USER: ${SPRING_DATASOURCE_USERNAME}
      MYSQL_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    restart: always
    networks:
      - test11

  test11_client_jenkins-service:
    container_name: test11_client_jenkins-service
    image: solnce52004/test11_client_jenkins:latest
    ports:
      - 5443:4443
    volumes:
      - .:/test11_client_jenkins
      - ./logs:/test11_client_jenkins/logs
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SSL_ALIAS: ${SSL_ALIAS}
      SSl_PASSWORD: ${SSl_PASSWORD}
    links:
      - mysql-service
    depends_on:
      - mysql-service
    restart: on-failure
    networks:
      - test11

networks:
  test11:
    external: true
    name: test11
    driver: bridge

