version: "3.9"
services:
  mysql:
    container_name: container_db
    build: ./docker/db
    ports:
      - "8306:3306"
    volumes:
      - /var/lib/mysql:/var/lib/mysql
      - /etc/mysql/conf.d:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: Zerkalo82
      MYSQL_DATABASE: Zerkalo82
      MYSQL_USER: jenkins
    restart: always

  test11_client_jenkins:
    container_name: container_client_app
    image: "solnce52004/test11_client_jenkins:latest"
    ports:
      - "5443:4443"
    volumes:
      - .:/test11_client_jenkins
      - ./logs:/test11_client_jenkins/logs
    depends_on:
      - mysql
    restart: always

