server:
  address: 0.0.0.0
  port: 4443
  compression:
    enabled: true
  http2:
    enabled: true

  error:
    whitelabel:
      enabled: false
  ssl:
    enabled: true
    key-alias: ${SSL_ALIAS}
    key-store: classpath:ssl/local-tomcat-private.p12
    key-store-type: PKCS12

    key-password: ${SSl_PASSWORD}
    key-store-password: ${SSl_PASSWORD}
    trust-store-password: changeit
#    trust-store: /usr/lib/jvm/java-11-openjdk-amd64/lib/security/cacerts

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_PASSWORD}
    password: ${SPRING_DATASOURCE_USERNAME}
    driver-class-name: com.mysql.cj.jdbc.Driver
#    hikari:
#      jdbc-url: ${SPRING_DATASOURCE_URL}
#      password: ${SPRING_DATASOURCE_PASSWORD}
#      username: ${SPRING_DATASOURCE_USERNAME}

  profiles:
    active: "dev"
  jpa:
    database-platform: "org.hibernate.dialect.MySQL8Dialect"
    generate-ddl: true

    properties:
      hibernate:
        default_batch_fetch_size: 20
        jdbc:
          batch_size: 10
          order_inserts: true
          order_updates: true

    # решает ошибку ClassCastException EntityManagerHolder
    open-in-view: false

  jackson:
    serialization:
      indent-output: true
      write_dates_as_timestamps: false

  flyway:
    enabled: false
    url: ${SPRING_DATASOURCE_URL}
    user: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  boot:
    admin:
      client:
        enabled: true
        url: "https://188.212.125.157:5555"
        instance:
          management-url: "https://188.212.125.157:5443"
          health-url: "https://188.212.125.157:5443/actuator/health"
          service-url: "https://188.212.125.157:5443"

logging:
  config: "classpath:log4j2.properties"
  level:
    ROOT: INFO
    org:
      springframework.web: DEBUG
      hibernate: INFO

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
# переменные окружения теперь пробрасываются через раздел environment в файле docker-compose.yaml
#