server:
  address: 0.0.0.0
  port: 4443
  compression:
    enabled: true
  http2:
    enabled: true
  error:
    whitelabel:
      enabled: false
  ssl:
    enabled: true
    key-alias: santomcat
    key-store: classpath:ssl/server.p12
    key-store-type: PKCS12

    key-password: ${SSl_PASSWORD}
    key-store-password: ${SSl_PASSWORD}
    trust-store-password: changeit
#    trust-store: /usr/lib/jvm/java-11-openjdk-amd64/lib/security/cacerts

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_PASSWORD}
    password: ${SPRING_DATASOURCE_USERNAME}
    driver-class-name: com.mysql.cj.jdbc.Driver
#    hikari:
#      jdbc-url: ${SPRING_DATASOURCE_URL}
#      password: ${SPRING_DATASOURCE_PASSWORD}
#      username: ${SPRING_DATASOURCE_USERNAME}

  profiles:
    active: "dev"
  jpa:
    database-platform: "org.hibernate.dialect.MySQL8Dialect"
    generate-ddl: true

    properties:
      hibernate:
        default_batch_fetch_size: 20
        jdbc:
          batch_size: 10
          order_inserts: true
          order_updates: true

    # решает ошибку ClassCastException EntityManagerHolder
    open-in-view: false
    hibernate:
      ddl-auto: none

  jackson:
    serialization:
      indent-output: true
      write_dates_as_timestamps: false

  flyway:
    enabled: true
    url: ${SPRING_DATASOURCE_URL}
    user: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    baseline-on-migrate: true

# для локального тестирования меняем: - порты,  -http, dev., ssl false
  boot:
    admin:
      client:
        enabled: true
#        урл админки (из контейнера торчит 5555, но nginx перенаправляет на 8000)!!!
        url: https://solnce52004.ga:8000
        instance:
#        урл клиента (из контейнера торчит 5443, но nginx перенаправляет на 443)!!!
#          обязательный путь для отображения всех метрик и графиков
#          в соответствии с настройками маски в настройках ниже
          management-url: https://solnce52004.ga:443/actuator
#          обязательный путь для получения метрик
          health-url: https://solnce52004.ga:443/actuator/health
#          необязательное название клиента для отображения в админке
          name: solnce52004
#          обязательный путь к метрикам клиента
          service-path: /actuator
#          домашняя страница сервиса (данного клиента)
          service-url: https://solnce52004.ga:443

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

logging:
  config: "classpath:log4j2.properties"
  level:
    ROOT: INFO
    org:
      springframework.web: DEBUG
      hibernate: INFO

# переменные окружения теперь пробрасываются через раздел environment в файле docker-compose.yaml
